
/**
 *This package contains the data classes that are necessary to organize the entities of an 
 *EntityStructureVersion with their properties and their relationship.
 *An concept of an ontology, a question, a response of a question or a fact of an EHR should be 
 *represented as {@link de.uni_leipzig.dbs.formRepository.dataModel.GenericEntity}. <br>
 *A GenericEntity object is defined by a unique id, which is 
 *automatically generated by the Datastore system, an accession string and a map of properties with their
 *corresponding values. The {@link de.uni_leipzig.dbs.formRepository.dataModel.GenericEntity} object are stored in an {@link de.uni_leipzig.dbs.formRepository.dataModel.EntityStructureVersion}<br>
 *Two GenericEntity objects may have an association with each other. These associations are represented by 
 *the {@link de.uni_leipzig.dbs.formRepository.dataModel.EntityRelationshipSet} that holds for each GenericEntity a set of target entities, which are associated
 *with the source entity. Moreover, the set of target entities is represented by a  {@link de.uni_leipzig.dbs.formRepository.dataModel.RelationshipSet}
 */
package de.uni_leipzig.dbs.formRepository.dataModel;